# Settings that are applied to the templates.

---
# Hostname is important as we need to delete an anonymous MySQL
# user that is created with this name, make sure you match this
# up with the output of the command 'hostname' on the server.
server_hostname: 'drupal8.dev'

init_method: 'default' # or supervisor

deploy_keys:
  - 'vagrant.pub'

# Apache2
apache_host: '*'
apache_port: "80"
apache_ssl_port: "443"
apache_server_admin: 'isaac.gasi@gmail.com'
apache_server_alias: 'drupal8.dev'
apache_packages:
  - apache2
  - libapache2-mod-php5
  - libapache2-mod-auth-mysql
apache_modules:
  - rewrite.load
  - alias.conf
  - authn_file.load
  - authz_host.load
  - autoindex.load
  - deflate.load
  - env.load
  - negotiation.conf
  - php5.load
  - rewrite.load
  - status.conf
  - alias.load
  # - authz_default.load
  # - authz_user.load
  - cgi.load
  - dir.conf
  - mime.conf
  - negotiation.load
  - reqtimeout.conf
  - setenvif.conf
  - status.load
  - auth_basic.load
  - authz_groupfile.load
  - autoindex.conf
  - deflate.conf
  - dir.load
  - mime.load
  - php5.conf
  - reqtimeout.load
  - setenvif.load

# MySQL Basic settings
mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_password: 'mysqlrootpassword'

# MySQL Fine Tuning
mysql_key_buffer: '16M'
mysql_max_allowed_packet: '128M'
mysql_thread_stack: '192K'
mysql_cache_size: 8
mysql_myisam_recover: 'BACKUP'
mysql_max_connections: 100
mysql_table_cache: 64
mysql_thread_concurrency: 10
mysql_query_cache_limit: '1M'
mysql_query_cache_size: '16M'
mysql_innodb_file_per_table: 'innodb_file_per_table'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
mysql_mysqldump_max_allowed_packet: '128M'
mysql_isamchk_key_buffer: '16M'

# PHP
php_packages:
  - php5
  - php5-common
  - php5-cli
  # - php5-suhosin
  - php-apc
  - php-pear
  - php5-gd
  - php5-memcache
  - php5-mcrypt
  - php5-gmp
  - php5-mysql
  - php5-curl
  - php5-xmlrpc
  - php5-imap
  - php-apc
  - php-soap
  - libgcrypt11-dev
  - zlib1g-dev

# php.ini values
php_post_max_size: '10M'
php_upload_max_filesize: '10M'
php_memory_limit: '128M'
php_html_errors: 'On'
php_max_execution_time: '90'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'Off'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'
php_date_timezone: 'US/Central'
php_zlib_output_compression: On
php_zlib_output_compression_level: 6

# apc.ini
apc_rfc1867: '1'
apc_shm_size: '128M'
apc_shm_segments: '1'
apc_num_files_hint: '0'

# Ruby & Bundler
ruby_version: ruby-1.9.3-p484
ruby_checksum: d684bc3a5ba72cda9ef30039f783c0f8cdc325bae5c8738c7bf05577cbe8f31d
ruby_download_location: http://cache.ruby-lang.org/pub/ruby/1.9/{{ ruby_version }}.tar.gz

vhost_sites:
  # - { 
  #     host: 'autowp.mysitebuild.com', 
  #     user: 'deploy',
  #     group: 'deploy',
  #     admin_email: 'dev@dev.mysitebuild.com',
  #     aliases: [ '*.autowp.mysitebuild.com', 'autowp.local' ],
  #     mysql_user: 'staging',
  #     mysql_database: 'wp_autowp',
  #     append_to_document_root: 'current/web'
  #   }

  # vsftpd
vsftpd_anonymous_enable: 'NO'
vsftpd_local_enable: 'YES'
vsftpd_write_enable: 'YES'
vsftpd_local_umask: '002'