---
- name: Install Composer
  shell: curl -sS  https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  tags: php

- name: Update Composer
  sudo: no
  shell: composer self-update
  tags: php

- name: Cloning/Updating Drush repo
  git: repo=git://github.com/drush-ops/drush.git
       dest=/usr/local/lib/drush
       version=master
       update=yes
  tags: php

- name: Making Drush executable
  file: path=/usr/local/lib/drush/drush mode=755
  tags: php

- name: Symlinking Drush
  file: src=/usr/local/lib/drush/drush dest=/usr/local/bin/drush state=link mode=755
  tags: php

- name: Installing Drush dependencies
  command: composer install chdir=/usr/local/lib/drush
  tags: php

# - name: Installing wp-cli
#   shell: curl -L https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar > /usr/local/bin/wp
#          creates=/usr/local/bin/wp

# - name: Making wp-cli executable
#   file: path=/usr/local/bin/wp mode=755

# - name: Install Capistrano
#   gem:
#     name: capistrano
#     state: latest
#     user_install: no

- name: Make Capistrano globally available
  file:
    path: /usr/local/bin/cap
    src: /opt/{{ ruby_version }}/bin/cap
    state: link