---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - common

- name: Install htpd or apache
  hosts: drupal8
  user: root

  roles:
    - httpd

- name: Install php and devtools
  hosts: drupal8
  user: root
  vars_files:
    - group_vars/php.yml
  roles:
    - ansible-role-php
  #  - php55w
    - devtools

- name: deploy MySQL and configure the databases
  hosts: drupal8
  user: root

  roles:
    - db

- name: Configure front end tools
  hosts: drupal8
  user: root

  roles:
    - rvm_io.rvm1-ruby
    - frontendtools

- name: Configure site
  hosts: drupal8
  user: root

  roles:
    - siteconfig
