#!/bin/sh

echo
echo " ********************************************************"
echo " * This server is configured using Ansible."
echo " * To change configuration,"
echo " * modify the playbooks and re-run the play."
echo " ********************************************************"
echo