---
- name: Installing Ansible Dependencies
  yum: name={{ item }} state=present
  with_items:
  - python-pycurl


- name: Installing Common Pacakges
  yum: name={{ item }} state=present
  tags: common
  with_items:
  - git
  - unzip
  - lzop
  - vim
  - tree
  - sendmail
  - curl

