---
- name: Installing Ansible Dependencies
  yum: name={{ item }} state=present
  with_items:
  - python-pycurl


- name: Installing Common Pacakges
  yum: name={{ item }} state=present
  tags: common
  with_items:
  - git
  - unzip
  - lzop
  - vim
  - tree
  - sendmail
  - curl
  - tar
  - wget
  - ntp

#
- name: add epel-release-6-8.noarch.rpm
  shell: rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  tags: php