---
# These tasks install the php modules.
- name: Add repo php 5.5
  shell: rpm -Uvh http://mirror.webtatic.com/yum/el6/latest.rpm
  tags: php

- name: Install php
  yum: name={{ item }} state=present
  with_items:
   - php55w
   - php55w-mysql
   - php55w-gd
   - php55w-mbstring
   - php55w-curl
   - php55w-common
   - php55w-dom
   - php55w-mcrypt
   - php55w-pdo
   - php55w-pecl-xdebug

- name: http service state
  service: name=httpd state=restarted enabled=yes
